import { ArrowLeft, Check, Download, FileWarning, ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import type { Scan } from "@/lib/types";
import RiskBadge from "@/components/RiskBadge";

export default function ResultReport({ scan, demo = false }: { scan: Scan; demo?: boolean }) {
  const navigate = useNavigate();
  const levelText = scan.risk_level === "safe" ? "LOW RISK" : scan.risk_level === "low" ? "LOW RISK" : scan.risk_level.toUpperCase().replace("SUSPICIOUS", "SUSPICIOUS").replace("HIGH", "HIGH RISK");
  const formattedDate = new Date(scan.created_at).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
  return (
    <section className="space-y-5" data-testid="analysis-result-report">
      <div className="flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={() => navigate(demo ? "/demo" : "/dashboard")} className="inline-flex items-center gap-2 text-xs font-bold text-[#52636d] hover:text-[#087f82]" data-testid="result-back-button"><ArrowLeft className="size-4" />{demo ? "Back to demo" : "Back to overview"}</button><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-[6px] border border-[#dce5ea] bg-white px-3 py-2 text-xs font-bold text-[#52636d] hover:border-[#087ea4] hover:text-[#075985]" data-testid="result-download-report-button"><Download className="size-3.5" />Download Report</button></div>
      <div className="border-b border-[#dce5ea] pb-6"><p className="mb-2 text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#087f82]" data-testid="result-complete-label">Analysis complete</p><h1 className="text-3xl font-extrabold tracking-[-0.04em] text-[#061827]" data-testid="result-page-title">Security analysis report</h1><p className="mt-2 max-w-2xl text-sm text-[#52636d]" data-testid="result-page-description">A structured assessment of the submitted {scan.scan_type} and the signals that shaped the result.</p></div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,.75fr)]">
        <div className="space-y-5">
          <div className="border border-[#dce5ea] bg-white p-5 sm:p-7" data-testid="result-risk-summary"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.16em] text-[#8fa2ad]" data-testid="result-risk-label">Risk assessment</p><div className="mt-3 flex items-center gap-3"><div className="size-3 rounded-full bg-[#9b3d35]" aria-hidden="true" /><h2 className="text-2xl font-extrabold tracking-[-0.03em]" data-testid="result-risk-level">{levelText}</h2></div><div className="mt-3"><RiskBadge risk={scan.risk_level} /></div></div><div className="relative grid size-[104px] place-items-center rounded-full" style={{ background: `conic-gradient(#087ea4 ${scan.risk_score}%, #eef3f6 0)` }} data-testid="result-risk-score-visual"><div className="grid size-[82px] place-items-center rounded-full bg-white"><span className="text-2xl font-black text-[#061827]" data-testid="result-risk-score">{scan.risk_score}</span><span className="-mt-2 text-[10px] font-bold text-[#8fa2ad]">/ 100</span></div></div></div><p className="mt-6 border-l-2 border-[#0fb7b5] pl-4 text-sm leading-6 text-[#52636d]" data-testid="result-analysis-summary">{scan.summary}</p></div>
          <div className="border border-[#dce5ea] bg-white p-5 sm:p-7" data-testid="result-indicators-section"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.15em] text-[#8fa2ad]">Signal review</p><h2 className="mt-1 text-lg font-extrabold" data-testid="result-indicators-heading">Threat indicators</h2></div><FileWarning className="size-5 text-[#087f82]" /></div>{scan.indicators.length ? <div className="divide-y divide-[#eef3f6]">{scan.indicators.map((indicator, index) => <div className="flex gap-4 py-4 first:pt-0 last:pb-0" key={indicator.id} data-testid={`threat-indicator-${index + 1}`}><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#eaf6f6] text-[11px] font-black text-[#087f82]">{String(index + 1).padStart(2, "0")}</span><div><h3 className="text-sm font-extrabold text-[#26343d]" data-testid={`threat-indicator-${index + 1}-title`}>{indicator.title}</h3><p className="mt-1 text-xs leading-5 text-[#52636d]" data-testid={`threat-indicator-${index + 1}-detail`}>{indicator.detail}</p></div></div>)}</div> : <div className="flex gap-3 text-sm text-[#52636d]" data-testid="result-no-indicators"><Check className="size-5 text-[#287b70]" /> No strong threat indicators detected.</div>}</div>
        </div>
        <div className="space-y-5"><div className="border border-[#b9dfdd] bg-[#effafa] p-5 sm:p-6" data-testid="result-recommendation"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 text-[#087f82]" /><div><p className="text-[11px] font-extrabold uppercase tracking-[0.15em] text-[#087f82]">Recommended action</p><p className="mt-3 text-sm font-semibold leading-6 text-[#26343d]" data-testid="result-recommendation-copy">{scan.recommendation}</p></div></div></div><div className="border border-[#dce5ea] bg-white p-5 sm:p-6" data-testid="result-metadata"><p className="text-[11px] font-extrabold uppercase tracking-[0.15em] text-[#8fa2ad]">Analysis metadata</p><dl className="mt-4 space-y-3 text-xs"><div className="flex justify-between gap-3"><dt className="text-[#8fa2ad]">Analysis type</dt><dd className="font-bold uppercase text-[#26343d]" data-testid="result-analysis-type">{scan.scan_type}</dd></div><div className="flex justify-between gap-3"><dt className="text-[#8fa2ad]">Scan ID</dt><dd className="max-w-[150px] truncate font-mono text-[10px] text-[#52636d]" data-testid="result-scan-id">{scan.id}</dd></div><div className="flex justify-between gap-3"><dt className="text-[#8fa2ad]">Timestamp</dt><dd className="text-right font-semibold text-[#26343d]" data-testid="result-timestamp">{formattedDate}</dd></div><div className="flex justify-between gap-3"><dt className="text-[#8fa2ad]">Status</dt><dd className="font-bold text-[#287b70]" data-testid="result-status">Completed</dd></div></dl></div><div className="border border-[#dce5ea] bg-[#08243a] p-5 text-white" data-testid="result-next-step"><p className="text-sm font-extrabold">{demo ? "Want to analyze your own content?" : "Need another check?"}</p><p className="mt-1 text-xs leading-5 text-[#b4cbd4]">{demo ? "Create an account to keep a private analysis history." : "Start a fresh analysis from the workspace."}</p><button type="button" onClick={() => navigate(demo ? "/register" : `/scan/${scan.scan_type}`)} className="mt-4 inline-flex items-center rounded-[6px] bg-[#0fb7b5] px-3.5 py-2.5 text-xs font-extrabold text-[#061827] hover:bg-[#7ce7e0]" data-testid="result-next-action-button">{demo ? "Create a Free Account" : "Scan Another"}</button></div></div>
      </div>
    </section>
  );
}