import { ArrowRight, FileWarning, Link2, LockKeyhole, Mail, MessageSquareText, ScanLine, ShieldCheck, TimerReset } from "lucide-react";
import { Link } from "react-router-dom";

const capabilities = [
  [Mail, "Emails", "Spot sender anomalies, phishing language, and suspicious links before you respond."],
  [MessageSquareText, "Messages", "Check scam patterns, social engineering, and unexpected requests."],
  [Link2, "URLs", "Inspect domains and paths for signals associated with impersonation pages."],
  [FileWarning, "Attachments", "Review risky file types without opening the file on your device."],
] as const;

export default function Home() {
  return (
    <main data-testid="home-page">
      <section className="relative overflow-hidden border-b border-[#dce5ea] bg-white" data-testid="home-hero-section">
        <div className="pointer-events-none absolute inset-0 opacity-[0.32] [background-image:linear-gradient(#dce5ea_1px,transparent_1px),linear-gradient(90deg,#dce5ea_1px,transparent_1px)] [background-size:56px_56px] [mask-image:linear-gradient(to_right,black,transparent_70%)]" />
        <div className="relative mx-auto grid max-w-[1240px] items-center gap-14 px-5 py-16 lg:grid-cols-[.88fr_1.12fr] lg:px-8 lg:py-24">
          <div data-testid="home-hero-copy"><div className="mb-6 inline-flex items-center gap-2 border-l-2 border-[#0fb7b5] pl-3 text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#087f82]" data-testid="home-hero-eyebrow"><span className="size-1.5 rounded-full bg-[#0fb7b5]" />Security analysis workspace</div><h1 className="max-w-[600px] text-[clamp(2.5rem,5vw,4.2rem)] font-extrabold leading-[1.02] tracking-[-0.06em] text-[#061827]" data-testid="home-hero-heading">Detect threats <span className="text-[#087ea4]">before</span> they reach you.</h1><p className="mt-6 max-w-[530px] text-[16px] leading-7 text-[#52636d]" data-testid="home-hero-description">Analyze emails, messages, URLs and attachments for spam, phishing and malicious content — quickly and clearly.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link to="/demo" className="inline-flex items-center gap-2 rounded-[7px] bg-[#087ea4] px-5 py-3 text-sm font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-[#075985]" data-testid="home-try-no-spam-button">Try NoSpamHQ <ArrowRight className="size-4" /></Link><Link to="/demo" className="inline-flex items-center rounded-[7px] border border-[#dce5ea] bg-white px-5 py-3 text-sm font-extrabold text-[#26343d] transition hover:border-[#087ea4] hover:text-[#075985]" data-testid="home-explore-demo-link">Explore Demo</Link></div><div className="mt-10 flex flex-wrap gap-5 text-[11px] font-bold text-[#8fa2ad]" data-testid="home-hero-trust-row"><span className="inline-flex items-center gap-2"><LockKeyhole className="size-3.5 text-[#087f82]" />Privacy-focused workflow</span><span className="inline-flex items-center gap-2"><TimerReset className="size-3.5 text-[#087f82]" />Clear results in seconds</span></div></div>
          <div className="relative" data-testid="home-hero-analysis-panel"><div className="absolute -inset-4 border border-[#0fb7b5]/20" /><div className="relative border border-[#193f55] bg-[#061827] p-5 text-white shadow-[0_20px_60px_rgba(6,24,39,.16)] sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center border border-[#0fb7b5]/50 bg-[#0b304b]"><ScanLine className="size-4 text-[#7ce7e0]" /></div><div><p className="text-xs font-extrabold" data-testid="hero-panel-title">Live analysis</p><p className="text-[10px] text-[#8fa2ad]">NoSpamHQ detection engine</p></div></div><span className="flex items-center gap-1.5 text-[10px] font-bold text-[#7ce7e0]"><span className="size-1.5 rounded-full bg-[#0fb7b5]" />READY</span></div><div className="border-b border-white/10 py-6"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fa2ad]">Input / suspicious email</p><h3 className="mt-2 text-lg font-bold" data-testid="hero-panel-input">Urgent: Your account requires verification</h3><p className="mt-2 text-xs leading-5 text-[#b8cbd3]">security-alert@example.com · received 2 minutes ago</p></div><div className="grid gap-3 py-5 text-xs"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fa2ad]">Signal review</p>{["Sender reputation", "Link analysis", "Content analysis", "Threat indicators"].map((label, index) => <div key={label} className="flex items-center justify-between border-b border-white/5 pb-2.5"><span className="text-[#dce5ea]">{label}</span><span className="flex items-center gap-2 font-mono text-[10px] text-[#7ce7e0]"><span className="size-1.5 rounded-full bg-[#0fb7b5]" />{index === 3 ? "3 FOUND" : index === 0 ? "REVIEW" : "FLAGGED"}</span></div>)}</div><div className="flex items-end justify-between border-t border-white/10 pt-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fa2ad]">Assessment</p><p className="mt-1 text-xl font-extrabold text-[#ffb85c]" data-testid="hero-panel-risk">HIGH RISK</p></div><div className="text-right"><p className="font-mono text-3xl font-black text-white">87<span className="text-base text-[#8fa2ad]">/100</span></p><p className="text-[10px] text-[#8fa2ad]">risk score</p></div></div></div><div className="absolute -bottom-5 -left-5 flex items-center gap-2 border border-[#b9dfdd] bg-[#effafa] px-3 py-2 text-[11px] font-bold text-[#087f82]" data-testid="hero-panel-status"><ShieldCheck className="size-4" />Actionable result</div></div>
        </div>
      </section>
      <section className="mx-auto max-w-[1240px] px-5 py-16 lg:px-8 lg:py-24" data-testid="home-capabilities-section"><div className="max-w-[600px]"><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#087f82]">What NoSpamHQ detects</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.045em] text-[#061827] sm:text-4xl" data-testid="home-capabilities-heading">One place to inspect suspicious content.</h2><p className="mt-4 text-sm leading-6 text-[#52636d]">Bring the first four threat surfaces into one clear workflow. No guesswork, no fear-based labels.</p></div><div className="mt-10 grid border-l border-t border-[#dce5ea] sm:grid-cols-2">{capabilities.map(([Icon, title, copy], index) => <div key={title} className="border-b border-r border-[#dce5ea] bg-white p-6 transition hover:bg-[#effafa] lg:p-8" data-testid={`home-capability-${title.toLowerCase()}-card`}><div className="flex items-start justify-between"><div className="grid size-10 place-items-center border border-[#b9dfdd] bg-[#effafa] text-[#087f82]"><Icon className="size-5" /></div><span className="font-mono text-[11px] font-bold text-[#8fa2ad]">0{index + 1}</span></div><h3 className="mt-8 text-lg font-extrabold" data-testid={`home-capability-${title.toLowerCase()}-title`}>{title}</h3><p className="mt-2 max-w-[260px] text-sm leading-6 text-[#52636d]">{copy}</p></div>)}</div></section>
      <section className="border-y border-[#dce5ea] bg-[#eef3f6]" data-testid="home-process-section"><div className="mx-auto max-w-[1240px] px-5 py-16 lg:px-8 lg:py-20"><div className="grid gap-10 lg:grid-cols-[.55fr_1.45fr]"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#087f82]">How it works</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.045em]">From uncertain to informed.</h2></div><div className="grid gap-0 border-l border-[#b9cbd3] md:grid-cols-3">{[["01", "Submit", "Paste, upload or enter the suspicious content."], ["02", "Analyze", "NoSpamHQ examines multiple threat indicators."], ["03", "Understand", "Receive a clear risk assessment and explanation."]].map(([number, title, copy]) => <div key={number} className="relative border-b border-[#b9cbd3] px-6 py-5 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="font-mono text-xs font-bold text-[#087f82]">{number}</span><h3 className="mt-10 text-lg font-extrabold" data-testid={`home-process-${number}-title`}>{title}</h3><p className="mt-2 text-sm leading-6 text-[#52636d]">{copy}</p></div>)}</div></div></div></section>
      <section className="bg-[#08243a] text-white" data-testid="home-security-section"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 py-16 lg:grid-cols-[.85fr_1.15fr] lg:px-8 lg:py-24"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#7ce7e0]">Why NoSpamHQ</p><h2 className="mt-3 max-w-[460px] text-3xl font-extrabold tracking-[-0.045em] sm:text-4xl" data-testid="home-security-heading">Security should be understandable.</h2><p className="mt-5 max-w-[480px] text-sm leading-7 text-[#b8cbd3]">A useful result goes beyond safe or unsafe. It explains what was detected, why it matters, and what to do next.</p><Link to="/security" className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-[#7ce7e0] hover:text-white" data-testid="home-security-link">Read our security principles <ArrowRight className="size-4" /></Link></div><div className="grid gap-px border border-white/10 bg-white/10 sm:grid-cols-2">{[["Fast analysis", "Get to a clear answer without a noisy report."], ["Clear explanations", "Understand the signals behind every assessment."], ["Multiple threat types", "Email, messages, URLs and attachments together."], ["Privacy focused", "Treat submitted content responsibly and transparently."]].map(([title, copy]) => <div key={title} className="bg-[#08243a] p-5 lg:p-7"><h3 className="text-sm font-extrabold text-white" data-testid={`home-advantage-${title.toLowerCase().replaceAll(" ", "-")}-title`}>{title}</h3><p className="mt-2 text-xs leading-5 text-[#9db5c2]">{copy}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-[1240px] px-5 py-16 lg:px-8 lg:py-20" data-testid="home-final-cta"><div className="flex flex-col items-start justify-between gap-7 border-l-2 border-[#0fb7b5] pl-6 sm:flex-row sm:items-center"><div><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-[#087f82]">Ready when you are</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-0.04em]" data-testid="home-cta-heading">Have something suspicious?</h2><p className="mt-2 text-sm text-[#52636d]">Run your first analysis with NoSpamHQ.</p></div><Link to="/demo" className="inline-flex items-center gap-2 rounded-[7px] bg-[#061827] px-5 py-3 text-sm font-extrabold text-white hover:bg-[#0b304b]" data-testid="home-final-demo-button">Try the Demo <ArrowRight className="size-4" /></Link></div></section>
    </main>
  );
}